# Generated by Django 3.0.2 on 2020-01-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name='offer',
            name='longtude',
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
    ]
